const DB='davomatpro', VERSION=1;
const seedGroups=[{id:'g1',name:'Frontend 24',room:'204-xona',color:'#635bff'},{id:'g2',name:'Grafik dizayn',room:'108-xona',color:'#18a978'},{id:'g3',name:'Rus tili A2',room:'302-xona',color:'#f59e42'}];
const names=['Aziza Karimova','Bekzod Rahimov','Dilshod Nurmatov','Madina Sobirova','Jasur Aliyev','Nilufar Hamidova','Sardor Tursunov','Malika Ismoilova','Akmal Qodirov','Zarina Abdullayeva','Otabek Mirzayev','Shahnoza Ergasheva'];
function open(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;['groups','students','attendance','settings'].forEach(x=>{if(!d.objectStoreNames.contains(x))d.createObjectStore(x,{keyPath:'id'})});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(store){const d=await open();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(store,val){const d=await open();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
async function remove(store,id){const d=await open();return new Promise(r=>{const q=d.transaction(store,'readwrite').objectStore(store).delete(id);q.onsuccess=r})}
async function delWhere(store,pred){const items=(await all(store)).filter(pred);if(!items.length)return 0;const d=await open();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');items.forEach(x=>t.objectStore(store).delete(x.id));t.oncomplete=()=>res(items.length);t.onerror=()=>rej(t.error)})}
function newId(prefix){return `${prefix}${Date.now().toString(36)}${Math.floor(Math.random()*1296).toString(36)}`}
async function init(){const initialized=(await all('settings')).some(x=>x.id==='initialized');if(!(await all('groups')).length&&!initialized){for(const g of seedGroups)await put('groups',g);let i=0;for(const g of seedGroups)for(const n of names.slice(0,g.id==='g1'?12:8))await put('students',{id:`s${++i}`,groupId:g.id,name:n,phone:'+998 90 123 45 67'});await put('settings',{id:'initialized',value:true});}}
async function clearAll(){const d=await open();return Promise.all(['groups','students','attendance','settings'].map(store=>new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=res;r.onerror=()=>rej(r.error)})))}
export const repo={init,all,put,remove,delWhere,newId,clearAll,async logs(date,groupId){return (await all('attendance')).filter(x=>x.date===date&&x.groupId===groupId)},async history(studentId){return (await all('attendance')).filter(x=>x.studentId===studentId).sort((a,b)=>b.date.localeCompare(a.date))},async mark(studentId,groupId,date,status){return put('attendance',{id:`${date}_${studentId}`,studentId,groupId,date,status,updatedAt:Date.now()})}};
