import React,{useCallback,useEffect,useState}from'react';import{Home,Users,CalendarCheck,Settings,Search,ChevronRight,ChevronLeft,WifiOff,MoreHorizontal,Plus,Check,Clock3,X,AlertCircle,Moon,Languages,Download,BookOpen,HardDrive,Trash2,Camera,UserPlus,ListChecks,NotebookPen,CircleSlash2,CheckCheck,RotateCcw,Timer,Pencil,CalendarDays,CircleDot}from'lucide-react';import{repo}from'./db/repository';import{dict}from'./i18n';
const today=new Date().toISOString().slice(0,10);const initials=n=>n.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();
/* --- daily task helpers: day keys, plural forms and per-task tallies --- */
const cap=k=>k[0].toUpperCase()+k.slice(1),taskLabel=(k,t)=>t['task'+cap(k)];
const parseDay=k=>{const[y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)};
const fmtDay=(k,locale,opt)=>parseDay(k).toLocaleDateString(locale||undefined,opt);
const shiftDay=(k,n)=>{const d=parseDay(k);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const plural=(n,t,key)=>{const one=t[key+'One'],few=t[key+'Few'],many=t[key+'Many'];if(!few)return `${n} ${one}`;const a=n%10,b=n%100;return `${n} ${a===1&&b!==11?one:a>=2&&a<=4&&(b<12||b>14)?few:many}`};
const width=(a,b)=>b?`${a/b*100}%`:'0%';
/* Count how many pupils of a group are done / partial / undone / not marked for one task. */
function tally(list,st={}){const c={done:0,partial:0,undone:0,none:0,total:list.length};list.forEach(s=>c[st[s.id]||'none']++);c.marked=c.done+c.partial+c.undone;c.pct=c.total?Math.round((c.done+c.partial*.5)/c.total*100):0;return c}
const byTask=rows=>rows.reduce((m,r)=>((m[r.taskId]||(m[r.taskId]={}))[r.studentId]=r.status,m),{});

const COLORS=['#635bff','#18a978','#f59e42','#eb5a70','#2f80ed','#0e9aa7','#c65b9d','#5b6472'];
const count=(n,t)=>`${n} ${n===1?t.pupilOne:t.pupils}`;
function Avatar({name,i=0,size='',src}){let colors=['violet','green','orange','blue','pink'];return <span className={`avatar ${colors[i%5]} ${size}`}>{src?<img src={src} alt={name}/>:initials(name)}</span>}
function Header({title,back,onBack,right}){return <header className="top"><div>{back?<button className="icon" onClick={onBack}><ChevronLeft/></button>:<div className="brand"><span className="logo"><CalendarCheck/></span><b>Davomat<span>Pro</span></b></div>}</div>{title&&<h2>{title}</h2>}<div>{right||<button className="avatar mini">OS</button>}</div></header>}
function Nav({tab,setTab,t}){return <nav className="bottom">{[[Home,'home',t.today],[Users,'groups',t.groups],[ListChecks,'tasks',t.tasks],[CalendarCheck,'attendance',t.attendance],[Settings,'settings',t.profile]].map(([I,k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I/><span>{l}</span></button>)}</nav>}
/* Bottom sheet used by every add/confirm dialog. Esc or tapping the shade closes it. */
function Sheet({title,sub,onClose,children}){useEffect(()=>{const k=e=>{if(e.key==='Escape')onClose()};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[onClose]);return <div className="modalShade" onClick={onClose}><section className="sheet" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header className="sheetHead"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div><button className="icon" onClick={onClose} aria-label="close"><X/></button></header><div className="sheetBody">{children}</div></section></div>}
function Empty({icon:I,title,text,action,onAction}){return <div className="emptyState"><span>{I}</span><b>{title}</b>{text&&<p>{text}</p>}{action&&<button onClick={onAction}>{action}</button>}</div>}
/* Create a group: name (required, unique), room, lesson time and a color. */
function GroupForm({t,groups,onClose,onCreated}){let[name,setName]=useState(''),[room,setRoom]=useState(''),[time,setTime]=useState(''),[color,setColor]=useState(COLORS[0]),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();if(busy)return;let n=name.trim().replace(/\s+/g,' ');
  if(n.length<2)return setErr(t.errGroupName);
  if(groups.some(g=>g.name.toLowerCase()===n.toLowerCase()))return setErr(t.errGroupExists);
  setBusy(true);try{let g={id:repo.newId('g'),name:n,room:room.trim(),time:time.trim(),color};await repo.put('groups',g);onCreated(g)}finally{setBusy(false)}
 }
 return <Sheet title={t.addGroup} sub={t.addGroupHint} onClose={onClose}><form onSubmit={submit} noValidate>
  <label className="field"><span>{t.groupName}</span><input value={name} onChange={e=>{setName(e.target.value);setErr('')}} placeholder={t.groupNamePh} maxLength={40} autoFocus/></label>
  <div className="fieldRow"><label className="field"><span>{t.room}</span><input value={room} onChange={e=>setRoom(e.target.value)} placeholder={t.roomPh} maxLength={24}/></label><label className="field"><span>{t.time}</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div>
  <span className="fieldLabel">{t.color}</span><div className="swatches">{COLORS.map(c=><button type="button" key={c} className={color===c?'on':''} style={{background:c}} onClick={()=>setColor(c)} aria-label={c}><Check/></button>)}</div>
  {err&&<p className="err"><AlertCircle/>{err}</p>}
  <button className="primaryBtn" type="submit" disabled={busy}>{busy?<Check/>:<Plus/>}{busy?t.saving:t.addGroup}</button>
 </form></Sheet>}
/* Add students to a group. The sheet stays open so several students can be added in a row. */
function StudentForm({t,groups,students,groupId,onClose,onCreated,onNeedGroup}){let[name,setName]=useState(''),[phone,setPhone]=useState(''),[gid,setGid]=useState(groupId||groups[0]?.id||''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[added,setAdded]=useState(0);
 let group=groups.find(g=>g.id===gid);
 async function submit(e){e.preventDefault();if(busy)return;let n=name.trim().replace(/\s+/g,' ');
  if(n.length<3)return setErr(t.errStudentName);
  if(!group)return setErr(t.errNoGroup);
  let p=phone.trim(),d=p.replace(/\D/g,'');
  if(p&&(d.length<7||d.length>15))return setErr(t.errPhone);
  if(students.some(s=>s.groupId===gid&&s.name.toLowerCase()===n.toLowerCase()))return setErr(t.errStudentExists);
  setBusy(true);try{let s={id:repo.newId('s'),groupId:gid,name:n,phone:p,createdAt:Date.now()};await repo.put('students',s);setAdded(a=>a+1);setName('');setPhone('');setErr('');onCreated(s)}finally{setBusy(false)}
 }
 return <Sheet title={t.addStudent} sub={group?`${group.name}${added?` · ${t.addedOne} ${added}`:''}`:t.addStudentHint} onClose={onClose}>
  {!groups.length?<Empty icon={<Users/>} title={t.noGroups} text={t.noGroupsText} action={t.addGroup} onAction={onNeedGroup}/>:<form onSubmit={submit} noValidate>
   <label className="field"><span>{t.studentName}</span><input value={name} onChange={e=>{setName(e.target.value);setErr('')}} placeholder={t.studentNamePh} maxLength={60} autoFocus/></label>
   <label className="field"><span>{t.phone}</span><input value={phone} onChange={e=>{setPhone(e.target.value);setErr('')}} placeholder={t.phonePh} inputMode="tel" maxLength={20}/></label>
   {groups.length>1&&<><span className="fieldLabel">{t.group}</span><div className="pickRow">{groups.map(g=><button type="button" key={g.id} className={gid===g.id?'on':''} onClick={()=>{setGid(g.id);setErr('')}}><i style={{background:g.color}}/>{g.name}</button>)}</div></>}
   {err&&<p className="err"><AlertCircle/>{err}</p>}
   <button className="primaryBtn" type="submit" disabled={busy}>{busy?<Check/>:<UserPlus/>}{busy?t.saving:t.addStudent}</button>
   {added>0&&<p className="hint"><Check/>{t.addedMany.replace('{n}',added)}</p>}
  </form>}
 </Sheet>}
function Confirm({t,title,text,onCancel,onConfirm}){return <div className="modalShade" onClick={onCancel}><section className="confirm" onClick={e=>e.stopPropagation()}><span className="warn"><Trash2/></span><h3>{title}</h3><p>{text}</p><div><button onClick={onCancel}>{t.cancel}</button><button className="danger" onClick={onConfirm}>{t.delete}</button></div></section></div>}
function Dashboard({groups,students,logs,tasks,marks,t,onGroup,setTab,onAddGroup,onOpenTask,onAddTask}){let counts={present:0,absent:0,late:0};logs.forEach(x=>counts[x.status]++);return <><Header/><main><section className="greeting"><div><p>{t.hello} 👋</p><h1>Otabek Sodiqov</h1></div><div className="datebox"><b>{new Date().getDate()}</b><span>{new Date().toLocaleString('uz',{month:'short'})}</span></div></section><section className="hero"><div className="heroDecor"></div><span className="eyebrow">{t.overview}</span><h2>{logs.length}<small> / {students.length}</small></h2><p>{t.students.toLowerCase()} {t.attendance.toLowerCase()}</p><div className="progress"><i style={{width:`${students.length?logs.length/students.length*100:0}%`}}/></div><button onClick={()=>setTab('attendance')}>{logs.length?t.continue:t.start}<ChevronRight/></button></section><h3 className="sectionTitle">{t.quick}</h3><div className="summary">{[['present',Check,counts.present],['absent',X,counts.absent],['late',Clock3,counts.late]].map(([k,I,n])=><article className={k} key={k}><span><I/></span><div><b>{n}</b><small>{t[k]}</small></div></article>)}</div><TaskSummary groups={groups} students={students} tasks={tasks} marks={marks} t={t} onOpen={onOpenTask} onAdd={onAddTask} setTab={setTab}/><div className="sectionHead"><h3>{t.groups}</h3><button onClick={()=>setTab('groups')}>{t.allGroups}<ChevronRight/></button></div><div className="groupList">{groups.slice(0,3).map((g,i)=>{let ss=students.filter(s=>s.groupId===g.id);return <button className="groupCard" key={g.id} onClick={()=>onGroup(g)}><span className="groupIcon" style={{background:g.color}}><BookOpen/></span><div><b>{g.name}</b><small>{[g.room,count(ss.length,t)].filter(Boolean).join(' · ')}</small></div><span className="time">{g.time||['09:00','11:30','14:00'][i]}</span><ChevronRight/></button>})}{!groups.length&&<Empty icon={<BookOpen/>} title={t.noGroups} text={t.noGroupsText} action={t.addGroup} onAction={onAddGroup}/>}</div></main></>}
function Groups({groups,students,t,onGroup,onMenu,onAddGroup}){let[q,setQ]=useState('');let n=q.trim().toLowerCase();let list=n?groups.filter(g=>`${g.name} ${g.room||''} ${students.filter(s=>s.groupId===g.id).map(s=>s.name).join(' ')}`.toLowerCase().includes(n)):groups;return <><Header title={t.groups}/><main><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.searchGroups}/>{q&&<button className="iconBtn tight" onClick={()=>setQ('')} aria-label={t.clear}><X/></button>}</div>{list.length?<div className="groupGrid">{list.map(g=><div className="groupCell" key={g.id}><button className="bigGroup" onClick={()=>onGroup(g)}><div className="bigTop"><span style={{background:g.color}}><BookOpen/></span></div><h3>{g.name}</h3><p>{[g.room,g.time].filter(Boolean).join(' · ')||t.noRoom}</p><div className="faces">{students.filter(s=>s.groupId===g.id).slice(0,4).map((s,j)=><Avatar key={s.id} name={s.name} i={j}/>)}<b>{students.filter(s=>s.groupId===g.id).length}</b></div></button><button className="moreBtn" onClick={()=>onMenu(g)} aria-label={t.groupMenu}><MoreHorizontal/></button></div>)}</div>:<Empty icon={<Search/>} title={q?t.noMatches:t.noGroups} text={q?t.noMatchesText:t.noGroupsText} action={q?t.clear:t.addGroup} onAction={()=>q?setQ(''):onAddGroup()}/>}</main><button className="fab" onClick={onAddGroup} aria-label={t.addGroup}><Plus/></button></>}
function Attendance({groups,students,t,selected,setSelected,onStudent,onAddStudent,onAddGroup,notify,reload,rev}){let [status,setStatus]=useState({}),[q,setQ]=useState(''),drag=React.useRef(null);let mine=students.filter(s=>s.groupId===selected?.id),list=mine.filter(s=>s.name.toLowerCase().includes(q.toLowerCase()));let done=list.filter(s=>status[s.id]).length;useEffect(()=>{if(selected)repo.logs(today,selected.id).then(rows=>setStatus(Object.fromEntries(rows.filter(a=>list.some(s=>s.id===a.studentId)).map(a=>[a.studentId,a.status]))))},[selected?.id,rev]);useEffect(()=>{const up=()=>{if(drag.current){drag.current=null;reload()}};addEventListener('pointerup',up);return()=>removeEventListener('pointerup',up)},[reload]);async function mark(s,k){setStatus(x=>({...x,[s.id]:k}));await repo.mark(s.id,selected.id,today,k);navigator.vibrate?.(10);if(!drag.current)reload()}async function markAll(k){setStatus(x=>({...x,...Object.fromEntries(list.map(s=>[s.id,k]))}));await Promise.all(list.map(s=>repo.mark(s.id,selected.id,today,k)));navigator.vibrate?.([15,30,15]);reload();notify(k==='present'?t.allPresent:t.allAbsent)}function begin(e,s,k){e.preventDefault();drag.current=k;mark(s,k)}
 return <><Header title={t.attendance}/><main className="attendance">
  <div className="chips">{groups.map(g=><button className={selected?.id===g.id?'active':''} onClick={()=>setSelected(g)} key={g.id}>{g.name}</button>)}<button className="chipAdd" onClick={onAddGroup} aria-label={t.addGroup}><Plus/></button></div>
  {selected&&<div className="classTitle"><div><h2>{selected.name}</h2><p>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</p></div><div className="titleRight"><span>{done}/{list.length}</span><button className="iconBtn" onClick={()=>onAddStudent(selected)} aria-label={t.addStudent}><UserPlus/></button></div></div>}
  {!!list.length&&<><div className="bulk"><button className="present" onClick={()=>markAll('present')}><Check/>{t.allPresent}</button><button className="absent" onClick={()=>markAll('absent')}><X/>{t.allAbsent}</button></div><p className="dragHint">↕ {t.dragHint}</p><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></div></>}
  {!!list.length&&<div className="studentList">{list.map((s,i)=><div className="student" key={s.id} onPointerEnter={()=>drag.current&&mark(s,drag.current)}><button className="identity" onClick={()=>onStudent(s)}><Avatar name={s.name} i={i}/><div><b>{s.name}</b><small>{s.phone||`#${String(i+1).padStart(2,'0')}`}</small></div></button><div className="marks">{[['present',Check],['late',Clock3],['absent',X]].map(([k,I])=><button aria-label={t[k]} className={`${k} ${status[s.id]===k?'active':''}`} onPointerDown={e=>begin(e,s,k)} key={k}><I/></button>)}</div></div>)}{selected&&!!list.length&&<button className="addRow" onClick={()=>onAddStudent(selected)}><Plus/>{t.addStudent}</button>}</div>}
  {selected&&!mine.length&&<Empty icon={<Users/>} title={t.noStudentsInGroup} text={t.noStudentsInGroupText} action={t.addStudent} onAction={()=>onAddStudent(selected)}/>}
  {selected&&!!mine.length&&!list.length&&<Empty icon={<Search/>} title={t.noMatches} text={t.noMatchesText} action={t.clear} onAction={()=>setQ('')}/>}
  {!groups.length&&<Empty icon={<BookOpen/>} title={t.noGroups} text={t.noGroupsText} action={t.addGroup} onAction={onAddGroup}/>}
 </main>{selected&&<button className="save" onClick={()=>notify(t.saved)}><Check/>{t.save}<span>{done}/{list.length}</span></button>}</>}
/* Day picker used by the tasks screen: 7 days around the selected one, arrows to travel further. */
function DateStrip({day,setDay,t}){const days=[-3,-2,-1,0,1,2,3].map(n=>shiftDay(day,n));
 return <div className="dateWrap"><div className="dateStrip">
  <button className="dsNav" onClick={()=>setDay(shiftDay(day,-1))} aria-label={t.prevDay}><ChevronLeft/></button>
  <div className="dsCells">{days.map(d=><button key={d} className={`dsCell ${d===day?'on':''}`} onClick={()=>setDay(d)}><span>{fmtDay(d,t.locale,{weekday:'short'}).replace('.','').slice(0,2)}</span><b>{+d.slice(8)}</b>{d===today&&<i className="dot"/>}</button>)}</div>
  <button className="dsNav" onClick={()=>setDay(shiftDay(day,1))} aria-label={t.nextDay}><ChevronRight/></button>
 </div>{day!==today&&<button className="dsToday" onClick={()=>setDay(today)}><CalendarDays/>{t.backToToday}</button>}</div>}
/* Create or edit one daily task: title, note, hand-in time and the group it belongs to. */
function TaskForm({t,groups,students,task,date,groupId,onClose,onSaved,onNeedGroup}){let[title,setTitle]=useState(task?.title||''),[note,setNote]=useState(task?.note||''),[deadline,setDeadline]=useState(task?.deadline||''),[gid,setGid]=useState(task?.groupId||groupId||groups[0]?.id||''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 let group=groups.find(g=>g.id===gid),pupils=students.filter(s=>s.groupId===gid).length,when=task?fmtDay(task.date,t.locale,{day:'numeric',month:'long'}):fmtDay(date,t.locale,{day:'numeric',month:'long'});
 async function submit(e){e.preventDefault();if(busy)return;let n=title.trim().replace(/\s+/g,' ');
  if(n.length<3)return setErr(t.errTaskTitle);
  if(!group)return setErr(t.errTaskGroup);
  setBusy(true);try{let k={...task,id:task?.id||repo.newId('k'),groupId:gid,date:task?.date||date,title:n,note:note.trim(),deadline,createdAt:task?.createdAt||Date.now(),updatedAt:Date.now()};
   await repo.put('tasks',k);onSaved(k,!!task)}finally{setBusy(false)}}
 return <Sheet title={task?t.editTask:t.addTask} sub={task?t.editTaskHint:group?`${group.name} · ${when}`:t.addTaskHint} onClose={onClose}>
  {!groups.length?<Empty icon={<BookOpen/>} title={t.noGroups} text={t.noGroupsText} action={t.addGroup} onAction={onNeedGroup}/>:<form onSubmit={submit} noValidate>
   <label className="field"><span>{t.taskTitle}</span><input value={title} onChange={e=>{setTitle(e.target.value);setErr('')}} placeholder={t.taskTitlePh} maxLength={70} autoFocus/></label>
   <label className="field note"><span>{t.taskNote}</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t.taskNotePh} rows={3} maxLength={220}/></label>
   <div className="fieldRow"><label className="field"><span>{t.taskDeadline}</span><input type="time" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><div className="field"><span>{t.students}</span><div className="staticField"><Users/>{count(pupils,t)}</div></div></div>
   {!task&&groups.length>1&&<><span className="fieldLabel">{t.group}</span><div className="pickRow">{groups.map(g=><button type="button" key={g.id} className={gid===g.id?'on':''} onClick={()=>{setGid(g.id);setErr('')}}><i style={{background:g.color}}/>{g.name}</button>)}</div></>}
   {err&&<p className="err"><AlertCircle/>{err}</p>}
   <button className="primaryBtn" type="submit" disabled={busy}>{busy||task?<Check/>:<Plus/>}{busy?t.saving:t.save}</button>
  </form>}
 </Sheet>}
/* One task card: title, note, a segmented done/partial/undone bar and the counters. */
function TaskCard({k,group,c,t,showGroup,onOpen,onMenu}){return <div className="taskCell">
 <button className="taskCard" onClick={()=>onOpen(k)}>
  <span className="taskIcon" style={{background:group?.color||'#8b91a2'}}><NotebookPen/></span>
  <span className="taskBody"><b>{k.title}</b>{k.note&&<p>{k.note}</p>}
   <span className="taskBar"><i className="done" style={{width:width(c.done,c.total)}}/><i className="partial" style={{width:width(c.partial,c.total)}}/><i className="undone" style={{width:width(c.undone,c.total)}}/></span>
   <span className="taskMeta">{showGroup&&<span className="pill group"><i style={{background:group?.color}}/>{group?.name}</span>}<span className="pill done"><Check/>{c.done}</span><span className="pill partial"><CircleSlash2/>{c.partial}</span><span className="pill undone"><X/>{c.undone}</span>{c.none>0&&<span className="pill none"><CircleDot/>{c.none}</span>}{k.deadline&&<span className="pill time"><Timer/>{k.deadline}</span>}</span>
  </span><ChevronRight/></button>
 <button className="moreBtn" onClick={()=>onMenu(k)} aria-label={t.taskMenu}><MoreHorizontal/></button></div>}
/* Tasks tab: group chips + day strip + the tasks of that day. */
function Tasks({groups,students,tasks,marks,day,setDay,t,group,setGroup,onOpen,onMenu,onAdd,onAddGroup}){
 const list=tasks.filter(k=>k.date===day&&(!group||k.groupId===group.id));
 const gOf=k=>groups.find(g=>g.id===k.groupId);
 const anyOnDay=tasks.some(k=>k.date===day);
 return <><Header title={t.tasks}/><main className="attendance">
  <div className="chips"><button className={!group?'active':''} onClick={()=>setGroup(null)}>{t.allGroups}</button>{groups.map(g=><button key={g.id} className={group?.id===g.id?'active':''} onClick={()=>setGroup(g)}>{g.name}</button>)}<button className="chipAdd" onClick={onAddGroup} aria-label={t.addGroup}><Plus/></button></div>
  <DateStrip day={day} setDay={setDay} t={t}/>
  <div className="classTitle"><div><h2>{fmtDay(day,t.locale,{day:'numeric',month:'long'})}</h2><p>{day===today?`${t.today} · ${fmtDay(day,t.locale,{weekday:'long'})}`:fmtDay(day,t.locale,{weekday:'long'})}{group?` · ${group.name}`:''}</p></div><div className="titleRight"><span>{plural(list.length,t,'tasks')}</span></div></div>
  {!groups.length?<Empty icon={<BookOpen/>} title={t.noGroups} text={t.noGroupsText} action={t.addGroup} onAction={onAddGroup}/>:list.length?<div className="taskList">{list.map(k=><TaskCard key={k.id} k={k} group={gOf(k)} c={tally(students.filter(s=>s.groupId===k.groupId),marks[k.id])} t={t} showGroup={!group} onOpen={onOpen} onMenu={onMenu}/>)}</div>:<Empty icon={<CalendarDays/>} title={anyOnDay?t.noTasks:t.noTasksOnDay} text={anyOnDay?t.noTasksText:t.noTasksOnDayText} action={t.addTask} onAction={onAdd}/>}
 </main>{!!groups.length&&<button className="fab" onClick={onAdd} aria-label={t.addTask}><Plus/></button>}</>}
/* Marking screen of one task: done / partial / undone for every pupil, with drag-to-paint. */
function TaskDetail({task,group,students,t,onBack,onMenu,onStudent,onAddStudent,notify,reload}){
 let[st,setSt]=useState({}),[q,setQ]=useState(''),drag=React.useRef(null);
 const all=students.filter(s=>s.groupId===task.groupId),list=all.filter(s=>s.name.toLowerCase().includes(q.trim().toLowerCase())),c=tally(all,st);
 useEffect(()=>{repo.taskProgress(task.id).then(rows=>setSt(Object.fromEntries(rows.map(r=>[r.studentId,r.status]))))},[task.id]);
 useEffect(()=>{const up=()=>{if(drag.current){drag.current=null;reload()}};addEventListener('pointerup',up);return()=>removeEventListener('pointerup',up)},[reload]);
 async function paint(s,k){setSt(x=>{const n={...x};if(k==='none')delete n[s.id];else n[s.id]=k;return n});await repo.markTask(task.id,s.id,task.groupId,task.date,k);if(!drag.current)reload()}
 function begin(e,s,k){e.preventDefault();const next=st[s.id]===k?'none':k;drag.current=next;navigator.vibrate?.(10);paint(s,next)}
 async function markAll(k){if(!list.length)return;setSt(x=>({...x,...Object.fromEntries(list.map(s=>[s.id,k]))}));await Promise.all(list.map(s=>repo.markTask(task.id,s.id,task.groupId,task.date,k)));navigator.vibrate?.([15,30,15]);reload();notify(k==='done'?t.allDone:t.allUndone)}
 async function clearMarks(){setSt({});await repo.delWhere('taskProgress',m=>m.taskId===task.id);reload();notify(t.marksCleared)}
 return <><Header back onBack={onBack} right={<button className="icon" onClick={onMenu} aria-label={t.more}><MoreHorizontal/></button>}/><main className="attendance">
  <section className="taskHero"><div className="heroDecor"/><span className="eyebrow">{[group?.name,fmtDay(task.date,t.locale,{weekday:'short',day:'numeric',month:'short'})].filter(Boolean).join(' · ')}</span><h2>{task.title}</h2>{task.note&&<p>{task.note}</p>}{task.deadline&&<span className="deadline"><Timer/>{t.taskDeadline} · {task.deadline}</span>}</section>
  <section className="statCard"><div className="ring" style={{'--p':`${c.pct}%`}}><div><b>{c.pct}%</b><small>{t.taskResults}</small></div></div><div className="statNums">{['done','partial','undone','none'].map(k=><div key={k}><i className={k}/><span><b>{c[k]}</b><small>{k==='none'?t.taskUnmarked:taskLabel(k,t)}</small></span></div>)}</div></section>
  {!all.length?<Empty icon={<Users/>} title={t.noStudentsInGroup} text={t.taskEmptyGroup} action={t.addStudent} onAction={()=>onAddStudent(group||{id:task.groupId})}/>:<>
   <div className="bulk bulk3"><button className="done" onClick={()=>markAll('done')}><CheckCheck/>{t.allDone}</button><button className="undone" onClick={()=>markAll('undone')}><X/>{t.allUndone}</button><button className="reset" onClick={clearMarks}><RotateCcw/>{t.clearMarks}</button></div>
   <p className="dragHint">↕ {t.taskMarkHint}</p>
   <div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/>{q&&<button className="iconBtn" onClick={()=>setQ('')} aria-label={t.clear}><X/></button>}</div>
   <div className="studentList">{list.map((s,i)=><div className="student" key={s.id} onPointerEnter={()=>drag.current&&paint(s,drag.current)}>
    <button className="identity" onClick={()=>onStudent(s)}><Avatar name={s.name} i={i}/><div><b>{s.name}</b><small className={st[s.id]||''}>{st[s.id]?taskLabel(st[s.id],t):s.phone||`#${String(i+1).padStart(2,'0')}`}</small></div></button>
    <div className="marks">{[['done',Check],['partial',CircleSlash2],['undone',X]].map(([k,I])=><button key={k} aria-label={taskLabel(k,t)} className={`${k} ${st[s.id]===k?'active':''}`} onPointerDown={e=>begin(e,s,k)}><I/></button>)}</div></div>)}
    {!!list.length&&<button className="addRow" onClick={()=>onAddStudent(group||{id:task.groupId})}><Plus/>{t.addStudent}</button>}</div>
   {!!all.length&&!list.length&&<Empty icon={<Search/>} title={t.noMatches} text={t.noMatchesText} action={t.clear} onAction={()=>setQ('')}/>}
  </>}
 </main></>}
/* Compact "today's tasks" card for the home screen. */
function TaskSummary({groups,students,tasks,marks,t,onOpen,onAdd,setTab}){
 const per=tasks.filter(k=>k.date===today).map(k=>({k,g:groups.find(x=>x.id===k.groupId),c:tally(students.filter(s=>s.groupId===k.groupId),marks[k.id])}));
 const c=per.reduce((a,x)=>({done:a.done+x.c.done,partial:a.partial+x.c.partial,undone:a.undone+x.c.undone,none:a.none+x.c.none,total:a.total+x.c.total,marked:a.marked+x.c.marked}),{done:0,partial:0,undone:0,none:0,total:0,marked:0});
 const pct=c.total?Math.round((c.done+c.partial*.5)/c.total*100):0;
 return <><div className="sectionHead"><h3>{t.todayTasks}</h3><button onClick={()=>setTab('tasks')}>{t.allTasks}<ChevronRight/></button></div>
 {per.length?<section className="taskSummary">
  <div className="tsHead"><span className="tsIcon"><ListChecks/></span><div><b>{plural(per.length,t,'tasks')}</b><small>{t.markedOf.replace('{a}',c.marked).replace('{b}',c.total)}</small></div><strong>{pct}%</strong></div>
  <div className="tsBar"><i className="done" style={{width:width(c.done,c.total)}}/><i className="partial" style={{width:width(c.partial,c.total)}}/><i className="undone" style={{width:width(c.undone,c.total)}}/></div>
  <div className="tsLegend">{['done','partial','undone'].map(k=><span key={k} className={k}>{k==='done'?<Check/>:k==='partial'?<CircleSlash2/>:<X/>}{taskLabel(k,t)} <b>{c[k]}</b></span>)}{c.none>0&&<span className="none"><CircleDot/>{t.taskUnmarked} <b>{c.none}</b></span>}</div>
  <div className="tsList">{per.slice(0,3).map(({k,g,c:cc})=><button key={k.id} onClick={()=>onOpen(k)}><i style={{background:g?.color||'#8b91a2'}}/><span><b>{k.title}</b><small>{[g?.name,`${cc.done}/${cc.total} ${t.taskDone.toLowerCase()}`].filter(Boolean).join(' · ')}</small></span><ChevronRight/></button>)}</div>
 </section>:<button className="taskCta" onClick={onAdd}><span><NotebookPen/></span><div><b>{t.noTasks}</b><small>{t.noTasksText}</small></div><Plus/></button>}</>}
function Student({student,t,onBack,onMenu}){let[hist,setHist]=useState([]),[th,setTh]=useState([]);useEffect(()=>{repo.history(student.id).then(setHist);repo.taskHistory(student.id).then(setTh)},[student]);let c=k=>hist.filter(x=>x.status===k).length;let tk={done:0,partial:0,undone:0,total:th.length};th.forEach(x=>{if(tk[x.status]!==undefined)tk[x.status]++});return <><Header back onBack={onBack} right={<button className="icon" onClick={onMenu} aria-label={t.more}><MoreHorizontal/></button>}/><main><section className="studentHero"><Avatar name={student.name} size="large"/><h2>{student.name}</h2><p>{student.phone||t.noPhone}</p></section><div className="period"><button className="active">{t.week}</button><button>{t.month}</button><button>{t.year}</button></div><section className="statCard"><div className="ring" style={{'--p':`${hist.length?c('present')/hist.length*100:76}%`}}><div><b>{hist.length?Math.round(c('present')/hist.length*100):76}%</b><small>{t.present}</small></div></div><div className="statNums">{['present','absent','late'].map(k=><div key={k}><i className={k}/><span><b>{c(k)}</b><small>{t[k]}</small></span></div>)}</div></section><h3 className="sectionTitle">{t.studentTasks}</h3><section className="taskStat"><div className="taskStatBar"><i className="done" style={{width:width(tk.done,tk.total)}}/><i className="partial" style={{width:width(tk.partial,tk.total)}}/><i className="undone" style={{width:width(tk.undone,tk.total)}}/></div><div className="taskStatNums">{[['done',Check],['partial',CircleSlash2],['undone',X]].map(([k,I])=><span key={k} className={k}><I/><b>{tk[k]}</b><small>{taskLabel(k,t)}</small></span>)}</div><p>{tk.total?plural(tk.total,t,'tasks'):t.noTasksForStudent}</p></section><h3 className="sectionTitle">{t.history}</h3><div className="history">{hist.length?hist.slice(0,8).map(h=><div key={h.id}><span className={`historyIcon ${h.status}`}>{h.status==='present'?<Check/>:h.status==='late'?<Clock3/>:<X/>}</span><div><b>{new Date(h.date).toLocaleDateString(undefined,{weekday:'long'})}</b><small>{new Date(h.date).toLocaleDateString()}</small></div><em className={h.status}>{t[h.status]}</em></div>):<div className="empty"><CalendarCheck/><p>{t.noHistory}</p></div>}</div></main></>}
function SettingsPage({t,lang,setLang,dark,setDark,profile,onEdit,onClear}){let[space,setSpace]=useState({usage:0,quota:0});useEffect(()=>{navigator.storage?.estimate().then(setSpace)},[]);let used=space.usage||0,quota=space.quota||0,pct=quota?Math.max(1,used/quota*100):0,fmt=n=>n>1073741824?(n/1073741824).toFixed(1)+' GB':(n/1048576).toFixed(1)+' MB';return <><Header title={t.profile}/><main><button className="profileCard profileButton" onClick={onEdit}><Avatar name={profile.name} src={profile.avatar} size="large"/><div><h3>{profile.name}</h3><p>Administrator</p></div><ChevronRight/></button><h4 className="label">{t.appearance}</h4><div className="settings"><div><span className="settingIcon"><Languages/></span><b>{t.language}</b><div className="seg"><button className={lang==='uz'?'active':''} onClick={()=>setLang('uz')}>UZ</button><button className={lang==='ru'?'active':''} onClick={()=>setLang('ru')}>RU</button></div></div><div><span className="settingIcon"><Moon/></span><b>{t.dark}</b><button className={`toggle ${dark?'on':''}`} onClick={()=>setDark(!dark)}><i/></button></div><div><span className="settingIcon"><Download/></span><b>{t.install}</b><ChevronRight/></div></div><h4 className="label">{t.storage}</h4><section className="storageCard"><div className="storageHead"><span><HardDrive/></span><div><b>{t.storage}</b><small>{fmt(used)} / {fmt(quota)}</small></div><strong>{pct.toFixed(1)}%</strong></div><div className="storageBar"><i style={{width:pct+'%'}}/></div><div className="storageMeta"><span>{t.used}<b>{fmt(used)}</b></span><span>{t.available}<b>{fmt(Math.max(0,quota-used))}</b></span></div></section><h4 className="label">{t.dataManagement}</h4><button className="dangerRow" onClick={onClear}><span><Trash2/></span><div><b>{t.clearDemo}</b><small>IndexedDB · Local</small></div><ChevronRight/></button></main></>}
function ProfileEdit({t,profile,setProfile,onBack,notify}){let[name,setName]=useState(profile.name),[avatar,setAvatar]=useState(profile.avatar);function photo(e){let f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){notify('Max 2 MB');return}let r=new FileReader();r.onload=()=>setAvatar(r.result);r.readAsDataURL(f)}async function save(){let p={id:'profile',name:name.trim()||profile.name,avatar};await repo.put('settings',p);setProfile(p);onBack();notify(t.done)}return <><Header title={t.profileEdit} back onBack={onBack}/><main><section className="photoEdit"><Avatar name={name} src={avatar} size="large"/><label><Camera/>{t.changePhoto}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={photo}/></label><small>{t.photoHint}</small></section><label className="field"><span>{t.fullName}</span><input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><button className="primaryBtn" onClick={save}><Check/>{t.save}</button></main></>}
export default function App(){
 const[groups,setGroups]=useState([]),[students,setStudents]=useState([]),[logs,setLogs]=useState([]),[tasks,setTasks]=useState([]),[marks,setMarks]=useState({}),[day,setDay]=useState(today),[taskGroup,setTaskGroup]=useState(null),[tab,setTab]=useState('home'),[selected,setSelected]=useState(null),[student,setStudent]=useState(null),[route,setRoute]=useState(location.pathname),[rev,setRev]=useState(0),[profile,setProfile]=useState({id:'profile',name:'Otabek Sodiqov',avatar:''}),[lang,setLang]=useState(localStorage.lang||'uz'),[dark,setDark]=useState(localStorage.dark==='true'),[online,setOnline]=useState(navigator.onLine),[toast,setToast]=useState('');const t=dict[lang];
 const reload=useCallback(async()=>{const [g,s,l,k,m]=await Promise.all([repo.all('groups'),repo.all('students'),repo.all('attendance'),repo.all('tasks'),repo.all('taskProgress')]);setGroups(g);setStudents(s);setLogs(l.filter(x=>x.date===today));setTasks(k.sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt));setMarks(byTask(m));setSelected(c=>c&&g.some(x=>x.id===c.id)?g.find(x=>x.id===c.id):g[0]||null);setTaskGroup(c=>c&&g.some(x=>x.id===c.id)?g.find(x=>x.id===c.id):null);setRev(v=>v+1)},[]);
 useEffect(()=>{repo.init().then(async()=>{await reload();setProfile((await repo.all('settings')).find(x=>x.id==='profile')||profile)})},[]);
 useEffect(()=>{localStorage.lang=lang;localStorage.dark=dark;document.documentElement.classList.toggle('dark',dark)},[lang,dark]);
 useEffect(()=>{let f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);return()=>{removeEventListener('online',f);removeEventListener('offline',f)}},[]);
 useEffect(()=>{const sync=()=>{const p=location.pathname;setRoute(p);if(p.startsWith('/student/')){setStudent(students.find(s=>s.id===p.split('/')[2])||null)}else{setStudent(null);const next=p.slice(1).split('/')[0];if(['home','groups','tasks','attendance','settings'].includes(next))setTab(next)}};sync();addEventListener('popstate',sync);return()=>removeEventListener('popstate',sync)},[students]);
 function go(path,state){history.pushState(state||{},'',path);dispatchEvent(new PopStateEvent('popstate'))}function back(){history.length>1?history.back():go('/'+tab)}function openGroup(g){setSelected(g);go('/attendance',{groupId:g.id})}function openTasks(g){setTaskGroup(g||null);setDay(today);go('/tasks')}function notify(x){setToast(x);setTimeout(()=>setToast(''),2200)}
 const groupMenuId=/^\/groups\/menu\/(.+)$/.exec(route)?.[1],groupDelId=/^\/groups\/delete\/(.+)$/.exec(route)?.[1],studentDelId=/^\/student\/([^/]+)\/delete$/.exec(route)?.[1],studentNew=/^\/students\/new(?:\/(.+))?$/.exec(route);
 const taskOpenId=/^\/tasks\/task\/([^/]+)$/.exec(route)?.[1],taskMenuId=/^\/tasks\/menu\/(.+)$/.exec(route)?.[1],taskEditId=/^\/tasks\/edit\/(.+)$/.exec(route)?.[1],taskDelId=/^\/tasks\/delete\/(.+)$/.exec(route)?.[1],taskNew=/^\/tasks\/new(?:\/(.+))?$/.exec(route);
 const menuGroup=groups.find(g=>g.id===groupMenuId),delGroup=groups.find(g=>g.id===groupDelId),delStudent=students.find(s=>s.id===studentDelId);
 const activeTask=tasks.find(k=>k.id===taskOpenId),menuTask=tasks.find(k=>k.id===taskMenuId),editTask=tasks.find(k=>k.id===taskEditId),delTask=tasks.find(k=>k.id===taskDelId);
 async function createGroup(g){await reload();setSelected(g);notify(t.groupAdded)}
 async function createStudent(){await reload();notify(t.studentAdded)}
 async function removeGroup(g){await Promise.all([repo.delWhere('students',s=>s.groupId===g.id),repo.delWhere('attendance',a=>a.groupId===g.id),repo.delWhere('taskProgress',m=>m.groupId===g.id),repo.delWhere('tasks',k=>k.groupId===g.id),repo.remove('groups',g.id)]);await reload();go('/groups');notify(t.groupDeleted)}
 async function removeStudent(s){await Promise.all([repo.delWhere('attendance',a=>a.studentId===s.id),repo.delWhere('taskProgress',m=>m.studentId===s.id),repo.remove('students',s.id)]);await reload();go('/attendance');notify(t.studentDeleted)}
 /* --- kunlik vazifalar: saqlash / o‘chirish / belgilash --- */
 async function saveTask(k,editing){await repo.put('tasks',k);setDay(k.date);await reload();notify(editing?t.taskSaved:t.taskAdded)}
 async function removeTask(k){await Promise.all([repo.delWhere('taskProgress',m=>m.taskId===k.id),repo.remove('tasks',k.id)]);await reload();go('/tasks');notify(t.taskDeleted)}
 function openTask(k){setTaskGroup(groups.find(g=>g.id===k.groupId)||null);go('/tasks/task/'+k.id)}
 async function clearData(){await repo.clearAll();await repo.put('settings',{id:'initialized',value:true});setGroups([]);setStudents([]);setLogs([]);setTasks([]);setMarks({});setDay(today);setTaskGroup(null);setSelected(null);setProfile({id:'profile',name:'Otabek Sodiqov',avatar:''});back();notify(t.resetDone)}
 let overlay=null;
 if(route==='/groups/new')overlay=<GroupForm t={t} groups={groups} onClose={back} onCreated={async g=>{back();await createGroup(g)}}/>;
 else if(menuGroup)overlay=<Sheet title={menuGroup.name} sub={count(students.filter(s=>s.groupId===menuGroup.id).length,t)} onClose={back}><div className="menu"><button onClick={()=>go('/students/new/'+menuGroup.id)}><UserPlus/>{t.addStudent}<ChevronRight/></button><button onClick={()=>openGroup(menuGroup)}><CalendarCheck/>{t.attendance}<ChevronRight/></button><button onClick={()=>openTasks(menuGroup)}><ListChecks/>{t.tasks}<ChevronRight/></button><button className="danger" onClick={()=>go('/groups/delete/'+menuGroup.id)}><Trash2/>{t.deleteGroup}</button></div></Sheet>;
 else if(studentNew)overlay=<StudentForm key={route} t={t} groups={groups} students={students} groupId={studentNew[1]||selected?.id} onClose={back} onCreated={createStudent} onNeedGroup={()=>go('/groups/new')}/>;
 else if(delGroup)overlay=<Confirm t={t} title={t.deleteGroup} text={t.deleteGroupText.replace('{n}',students.filter(s=>s.groupId===delGroup.id).length)} onCancel={back} onConfirm={()=>removeGroup(delGroup)}/>;
 else if(delStudent)overlay=<Confirm t={t} title={t.deleteStudent} text={t.deleteStudentText} onCancel={back} onConfirm={()=>removeStudent(delStudent)}/>;
 else if(taskNew)overlay=<TaskForm key={route} t={t} groups={groups} students={students} date={day} groupId={taskNew[1]||taskGroup?.id||selected?.id} onClose={back} onSaved={async(k,e)=>{back();await saveTask(k,e)}} onNeedGroup={()=>go('/groups/new')}/>;
 else if(editTask)overlay=<TaskForm key={route} t={t} groups={groups} students={students} task={editTask} onClose={back} onSaved={async(k,e)=>{back();await saveTask(k,e)}} onNeedGroup={()=>go('/groups/new')}/>;
 else if(menuTask)overlay=<Sheet title={menuTask.title} sub={[groups.find(g=>g.id===menuTask.groupId)?.name,fmtDay(menuTask.date,t.locale,{day:'numeric',month:'long'})].filter(Boolean).join(' · ')} onClose={back}><div className="menu"><button onClick={()=>go('/tasks/task/'+menuTask.id)}><ListChecks/>{t.openTask}<ChevronRight/></button><button onClick={()=>go('/tasks/edit/'+menuTask.id)}><Pencil/>{t.editTask}<ChevronRight/></button><button className="danger" onClick={()=>go('/tasks/delete/'+menuTask.id)}><Trash2/>{t.deleteTask}</button></div></Sheet>;
 else if(delTask)overlay=<Confirm t={t} title={t.deleteTask} text={t.deleteTaskText} onCancel={back} onConfirm={()=>removeTask(delTask)}/>;
 else if(route==='/settings/clear')overlay=<Confirm t={t} title={t.clearDemo} text={t.clearConfirm} onCancel={back} onConfirm={clearData}/>;
 let body=activeTask?<TaskDetail task={activeTask} group={groups.find(g=>g.id===activeTask.groupId)} students={students} t={t} onBack={()=>history.back()} onMenu={()=>go('/tasks/menu/'+activeTask.id)} onStudent={s=>go('/student/'+s.id)} onAddStudent={g=>go(g?'/students/new/'+g.id:'/students/new')} notify={notify} reload={reload}/>:student?<Student student={student} t={t} onBack={()=>history.back()} onMenu={()=>go(`/student/${student.id}/delete`)}/>:route==='/settings/profile'?<ProfileEdit {...{t,profile,setProfile,notify}} onBack={back}/>:<><>{!online&&<div className="offline"><WifiOff/>{t.offline}</div>}{tab==='home'&&<Dashboard {...{groups,students,logs,tasks,marks,t,setTab}} onGroup={openGroup} onAddGroup={()=>go('/groups/new')} onOpenTask={openTask} onAddTask={()=>go(taskGroup?'/tasks/new/'+taskGroup.id:'/tasks/new')}/>}{tab==='groups'&&<Groups {...{groups,students,t}} onGroup={openGroup} onMenu={g=>go('/groups/menu/'+g.id)} onAddGroup={()=>go('/groups/new')}/>}{tab==='tasks'&&<Tasks {...{groups,students,tasks,marks,day,setDay,t}} group={taskGroup} setGroup={setTaskGroup} onOpen={openTask} onMenu={k=>go('/tasks/menu/'+k.id)} onAdd={()=>go(taskGroup?'/tasks/new/'+taskGroup.id:'/tasks/new')} onAddGroup={()=>go('/groups/new')}/>} {tab==='attendance'&&<Attendance {...{groups,students,t,selected,setSelected,notify,reload,rev}} onStudent={s=>go('/student/'+s.id)} onAddStudent={g=>go(g?'/students/new/'+g.id:'/students/new')} onAddGroup={()=>go('/groups/new')}/>}{tab==='settings'&&<SettingsPage {...{t,lang,setLang,dark,setDark,profile}} onEdit={()=>go('/settings/profile')} onClear={()=>go('/settings/clear')}/>}<Nav tab={tab} setTab={x=>go('/'+x)} t={t}/></></>;
 return <div className="app">{body}{overlay}{toast&&<div className="toast"><Check/>{toast}</div>}</div>}
